ARG base_container=python:3.11-bookworm
FROM ${base_container}
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt-get update && apt-get upgrade -y && \
    apt-get -y install --no-install-recommends git build-essential libsaga-dev saga cmake ca-certificates zip&& \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install -r requirements.txt
    
