name: 'Build on debian bullseye in container'

on:
  push:
    branches: [main, gha]

jobs:
  bullseye-container-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [bullseye, bookworm, focal]
    container:
      image: ghcr.io/johanvdw/saga-watem-build-${{ matrix.os }}
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: run cmake
      run: |
        mkdir build
        cd build
        cmake ..
        make
        cd ..
        pytest-3
      
  bullseye-container-build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [bullseye, bookworm, focal]
    container:
      image: ghcr.io/johanvdw/saga-watem-build-${{ matrix.os }}
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: run cmake
      run: |
        git pull
        git fetch --tags
        dch --newversion $(git describe --tags)  "autobuild $(git describe --tags)"
        debuild -b

