on:
  push:
    tags:
    - '*'

name: Create Release

jobs:
  build-linux:
    uses: ./.github/workflows/cmake-linux.yml
  build-windows:
    uses: ./.github/workflows/cmake-windows.yml
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
    - build-linux
    - build-windows
    steps:
      - uses: actions/checkout@v4
      - name: fetch linux builds (zip)
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: cmake-linux.yml
          path: linux
      - name: fetch linux builds (deb)
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: cmake-linux.yml
          path: deb
      - name: fetch windows builds
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: cmake-windows.yml
          path: dll
      - name: Gather all release files
        run: |
          mkdir release-files
          find dll/ linux/ deb/ -type f -exec cp --parents {} release-files/ \;
      - uses: ncipollo/release-action@v1
        with:
          artifacts: |
            dll/**/*.zip
            linux/**/*.zip
            deb/**/*.deb
          omitBody: true
